#include<iostream.h>
#include<conio.h>
#include<graphics.h>
#include<stdio.h>
#include<stdlib.h>
#include<math.h>
void main()
{
clrscr();
int gd=DETECT,gm;
initgraph(&gd,&gm,"C\\TURBOC3\\BGI");
	putpixel(100+50,200+100,RED);
       /*	putpixel(y+cx,x+cy,GREEN);
	putpixel(y+cx,-x+cy,RED);
	putpixel(x+cx,-y+cy,GREEN);
	putpixel(-x+cx,-y+cy,RED);
	putpixel(-y+cx,-x+cy,GREEN);
	putpixel(-y+cx,x+cy,RED);
	putpixel(-x+cx,y+cy,GREEN);

		  */






getch();
closegraph();
}
